import 'package:flutter/material.dart';
import 'package:flutterapp/flutter_appapp/generatededitwinewidget/generated/GeneratedGroup1543Widget.dart';
import 'package:flutterapp/flutter_appapp/generatededitwinewidget/generated/GeneratedGroup1536Widget.dart';
import 'package:flutterapp/flutter_appapp/generatededitwinewidget/generated/GeneratedGroup1540Widget.dart';
import 'package:flutterapp/flutter_appapp/generatededitwinewidget/generated/GeneratedGroup1544Widget.dart';
import 'package:flutterapp/flutter_appapp/generatededitwinewidget/generated/GeneratedFooterWidget2.dart';
import 'package:flutterapp/flutter_appapp/generatededitwinewidget/generated/GeneratedGroup1545Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/flutter_appapp/generatededitwinewidget/generated/GeneratedGroup1541Widget.dart';
import 'package:flutterapp/flutter_appapp/generatededitwinewidget/generated/GeneratedGroup1542Widget.dart';
import 'package:flutterapp/flutter_appapp/generatededitwinewidget/generated/GeneratedGroup1535Widget.dart';
import 'package:flutterapp/flutter_appapp/generatededitwinewidget/generated/GeneratedGroup1546Widget.dart';
import 'package:flutterapp/flutter_appapp/generatededitwinewidget/generated/GeneratedGroup1538Widget.dart';
import 'package:flutterapp/flutter_appapp/generatededitwinewidget/generated/GeneratedGroup1537Widget.dart';
import 'package:flutterapp/flutter_appapp/generatededitwinewidget/generated/GeneratedGroup1539Widget.dart';
import 'package:flutterapp/flutter_appapp/generatededitwinewidget/generated/GeneratedMODIFICAVINOWidget.dart';

/* Frame Edit Wine
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEditWineWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 158, 163, 247),
              Color.fromARGB(255, 255, 255, 255)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7743589743589744;

                  final double height =
                      constraints.maxHeight * 0.04383886255924171;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.07692307692307693,
                        y: constraints.maxHeight * 0.06516587677725119,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMODIFICAVINOWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 779.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 65.0,
                child: GeneratedFooterWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 111.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1535Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1536Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 195.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1537Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 237.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1538Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1539Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1540Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 363.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1541Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1542Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1543Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1544Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 531.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1545Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 573.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 119.0,
                child: GeneratedGroup1546Widget(),
              )
            ]),
      ),
    ));
  }
}
