import 'package:flutter/material.dart';
import 'package:flutterapp/flutter_appapp/generatedaddwinewidget/generated/GeneratedGroup1551Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedaddwinewidget/generated/GeneratedGroup1559Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedaddwinewidget/generated/GeneratedGroup1548Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedaddwinewidget/generated/GeneratedGroup1558Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedaddwinewidget/generated/GeneratedGroup1557Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedaddwinewidget/generated/GeneratedGroup1547Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedaddwinewidget/generated/GeneratedGroup1552Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedaddwinewidget/generated/GeneratedAGGIUNGIVINOWidget.dart';
import 'package:flutterapp/flutter_appapp/generatedaddwinewidget/generated/GeneratedGroup1553Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedaddwinewidget/generated/GeneratedFooterWidget1.dart';
import 'package:flutterapp/flutter_appapp/generatedaddwinewidget/generated/GeneratedGroup1555Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/flutter_appapp/generatedaddwinewidget/generated/GeneratedGroup1556Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedaddwinewidget/generated/GeneratedGroup1550Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedaddwinewidget/generated/GeneratedGroup1549Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedaddwinewidget/generated/GeneratedGroup1554Widget.dart';

/* Frame Add Wine
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddWineWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 158, 163, 247),
              Color.fromARGB(255, 255, 255, 255)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7743589743589744;

                  final double height =
                      constraints.maxHeight * 0.04383886255924171;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.07692307692307693,
                        y: constraints.maxHeight * 0.06516587677725119,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedAGGIUNGIVINOWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 779.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 65.0,
                child: GeneratedFooterWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 111.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1547Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 707.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1559Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1548Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 195.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1549Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 237.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1550Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1551Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1552Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 363.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1553Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1554Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1555Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1556Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 531.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 27.0,
                child: GeneratedGroup1557Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 573.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 119.0,
                child: GeneratedGroup1558Widget(),
              )
            ]),
      ),
    ));
  }
}
