import 'package:flutter/material.dart';

/* Text CRUSCOTTO DELLA CANTINA
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCRUSCOTTODELLACANTINAWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Align(
      alignment: Alignment.centerLeft,
      child: Text(
        '''CRUSCOTTO DELLA CANTINA''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        style: TextStyle(
          height: 1.171875,
          fontSize: 17.0,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
          color: Color.fromARGB(255, 52, 42, 114),

          /* letterSpacing: 0.0, */
        ),
      ),
    ));
  }
}
