import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/flutter_appapp/generatedwinewidget2/generated/GeneratedGroup1527Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedwinewidget2/generated/GeneratedGroup1526Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedwinewidget2/generated/GeneratedFooterWidget3.dart';
import 'package:flutterapp/flutter_appapp/generatedwinewidget2/generated/GeneratedVectorWidget13.dart';
import 'package:flutterapp/flutter_appapp/generatedwinewidget2/generated/GeneratedGroup1525Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedwinewidget2/generated/GeneratedGroup1524Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedwinewidget2/generated/GeneratedVINOWidget.dart';
import 'package:flutterapp/flutter_appapp/generatedwinewidget2/generated/GeneratedGroup1530Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedwinewidget2/generated/GeneratedGroup1533Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedwinewidget2/generated/GeneratedGroup1528Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedwinewidget2/generated/GeneratedGroup1532Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedwinewidget2/generated/GeneratedGroup1529Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedwinewidget2/generated/GeneratedWineryWidget2.dart';
import 'package:flutterapp/flutter_appapp/generatedwinewidget2/generated/GeneratedGroup1523Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedwinewidget2/generated/GeneratedGroup1531Widget.dart';
import 'package:flutterapp/flutter_appapp/generatedwinewidget2/generated/GeneratedGroup1534Widget.dart';

/* Frame Wine
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWineWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 158, 163, 247),
              Color.fromARGB(255, 255, 255, 255)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.782051282051282;

                  final double height =
                      constraints.maxHeight * 0.04739336492890995;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.07692307692307693,
                        y: constraints.maxHeight * 0.06516587677725119,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedVINOWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 779.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 65.0,
                child: GeneratedFooterWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.05128205128205128;
                  double scaleX = (constraints.maxWidth * percentWidth) / 20.0;

                  double percentHeight = 0.023696682464454975;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 20.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8871794871794871,
                        translateY: constraints.maxHeight * 0.07345971563981042,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget13())
                  ]);
                }),
              ),
              Positioned(
                left: 35.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 32.0,
                child: GeneratedWineryWidget2(),
              ),
              Positioned(
                left: 35.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 27.0,
                child: GeneratedGroup1523Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 27.0,
                child: GeneratedGroup1524Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 27.0,
                child: GeneratedGroup1525Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 27.0,
                child: GeneratedGroup1526Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 27.0,
                child: GeneratedGroup1527Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 322.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 27.0,
                child: GeneratedGroup1528Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 27.0,
                child: GeneratedGroup1529Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 27.0,
                child: GeneratedGroup1530Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 27.0,
                child: GeneratedGroup1531Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 27.0,
                child: GeneratedGroup1532Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 532.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 27.0,
                child: GeneratedGroup1533Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 574.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 27.0,
                child: GeneratedGroup1534Widget(),
              )
            ]),
      ),
    ));
  }
}
